# GENETARED BY NNDCT, DO NOT EDIT!

import torch
from torch import tensor
import pytorch_nndct as py_nndct

class DetectionModel(py_nndct.nn.NndctQuantModel):
    def __init__(self):
        super(DetectionModel, self).__init__()
        self.module_0 = py_nndct.nn.Input() #DetectionModel::input_0(DetectionModel::nndct_input_0)
        self.module_1 = py_nndct.nn.Conv2d(in_channels=3, out_channels=16, kernel_size=[6, 6], stride=[2, 2], padding=[2, 2], dilation=[1, 1], groups=1, bias=True) #DetectionModel::DetectionModel/Conv[model]/Conv[0]/Conv2d[conv]/ret.3(DetectionModel::nndct_conv2d_1)
        self.module_2 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=True) #DetectionModel::DetectionModel/Conv[model]/Conv[0]/LeakyReLU[act]/8714(DetectionModel::nndct_leaky_relu_2)
        self.module_3 = py_nndct.nn.Conv2d(in_channels=16, out_channels=32, kernel_size=[3, 3], stride=[2, 2], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #DetectionModel::DetectionModel/Conv[model]/Conv[1]/Conv2d[conv]/ret.5(DetectionModel::nndct_conv2d_3)
        self.module_4 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=True) #DetectionModel::DetectionModel/Conv[model]/Conv[1]/LeakyReLU[act]/8736(DetectionModel::nndct_leaky_relu_4)
        self.module_5 = py_nndct.nn.Conv2d(in_channels=32, out_channels=16, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #DetectionModel::DetectionModel/C3[model]/C3[2]/Conv[cv1]/Conv2d[conv]/ret.7(DetectionModel::nndct_conv2d_5)
        self.module_6 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=True) #DetectionModel::DetectionModel/C3[model]/C3[2]/Conv[cv1]/LeakyReLU[act]/8758(DetectionModel::nndct_leaky_relu_6)
        self.module_7 = py_nndct.nn.Conv2d(in_channels=16, out_channels=16, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #DetectionModel::DetectionModel/C3[model]/C3[2]/Sequential[m]/Bottleneck[0]/Conv[cv1]/Conv2d[conv]/ret.9(DetectionModel::nndct_conv2d_7)
        self.module_8 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=True) #DetectionModel::DetectionModel/C3[model]/C3[2]/Sequential[m]/Bottleneck[0]/Conv[cv1]/LeakyReLU[act]/8780(DetectionModel::nndct_leaky_relu_8)
        self.module_9 = py_nndct.nn.Conv2d(in_channels=16, out_channels=16, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #DetectionModel::DetectionModel/C3[model]/C3[2]/Sequential[m]/Bottleneck[0]/Conv[cv2]/Conv2d[conv]/ret.11(DetectionModel::nndct_conv2d_9)
        self.module_10 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=True) #DetectionModel::DetectionModel/C3[model]/C3[2]/Sequential[m]/Bottleneck[0]/Conv[cv2]/LeakyReLU[act]/8802(DetectionModel::nndct_leaky_relu_10)
        self.module_11 = py_nndct.nn.Add() #DetectionModel::DetectionModel/C3[model]/C3[2]/Sequential[m]/Bottleneck[0]/ret.13(DetectionModel::nndct_elemwise_add_11)
        self.module_12 = py_nndct.nn.Conv2d(in_channels=32, out_channels=16, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #DetectionModel::DetectionModel/C3[model]/C3[2]/Conv[cv2]/Conv2d[conv]/ret.15(DetectionModel::nndct_conv2d_12)
        self.module_13 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=True) #DetectionModel::DetectionModel/C3[model]/C3[2]/Conv[cv2]/LeakyReLU[act]/8827(DetectionModel::nndct_leaky_relu_13)
        self.module_14 = py_nndct.nn.Cat() #DetectionModel::DetectionModel/C3[model]/C3[2]/ret.17(DetectionModel::nndct_concat_14)
        self.module_15 = py_nndct.nn.Conv2d(in_channels=32, out_channels=32, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #DetectionModel::DetectionModel/C3[model]/C3[2]/Conv[cv3]/Conv2d[conv]/ret.19(DetectionModel::nndct_conv2d_15)
        self.module_16 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=True) #DetectionModel::DetectionModel/C3[model]/C3[2]/Conv[cv3]/LeakyReLU[act]/8853(DetectionModel::nndct_leaky_relu_16)
        self.module_17 = py_nndct.nn.Conv2d(in_channels=32, out_channels=64, kernel_size=[3, 3], stride=[2, 2], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #DetectionModel::DetectionModel/Conv[model]/Conv[3]/Conv2d[conv]/ret.21(DetectionModel::nndct_conv2d_17)
        self.module_18 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=True) #DetectionModel::DetectionModel/Conv[model]/Conv[3]/LeakyReLU[act]/8875(DetectionModel::nndct_leaky_relu_18)
        self.module_19 = py_nndct.nn.Conv2d(in_channels=64, out_channels=32, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #DetectionModel::DetectionModel/C3[model]/C3[4]/Conv[cv1]/Conv2d[conv]/ret.23(DetectionModel::nndct_conv2d_19)
        self.module_20 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=True) #DetectionModel::DetectionModel/C3[model]/C3[4]/Conv[cv1]/LeakyReLU[act]/8897(DetectionModel::nndct_leaky_relu_20)
        self.module_21 = py_nndct.nn.Conv2d(in_channels=32, out_channels=32, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #DetectionModel::DetectionModel/C3[model]/C3[4]/Sequential[m]/Bottleneck[0]/Conv[cv1]/Conv2d[conv]/ret.25(DetectionModel::nndct_conv2d_21)
        self.module_22 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=True) #DetectionModel::DetectionModel/C3[model]/C3[4]/Sequential[m]/Bottleneck[0]/Conv[cv1]/LeakyReLU[act]/8919(DetectionModel::nndct_leaky_relu_22)
        self.module_23 = py_nndct.nn.Conv2d(in_channels=32, out_channels=32, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #DetectionModel::DetectionModel/C3[model]/C3[4]/Sequential[m]/Bottleneck[0]/Conv[cv2]/Conv2d[conv]/ret.27(DetectionModel::nndct_conv2d_23)
        self.module_24 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=True) #DetectionModel::DetectionModel/C3[model]/C3[4]/Sequential[m]/Bottleneck[0]/Conv[cv2]/LeakyReLU[act]/8941(DetectionModel::nndct_leaky_relu_24)
        self.module_25 = py_nndct.nn.Add() #DetectionModel::DetectionModel/C3[model]/C3[4]/Sequential[m]/Bottleneck[0]/ret.29(DetectionModel::nndct_elemwise_add_25)
        self.module_26 = py_nndct.nn.Conv2d(in_channels=32, out_channels=32, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #DetectionModel::DetectionModel/C3[model]/C3[4]/Sequential[m]/Bottleneck[1]/Conv[cv1]/Conv2d[conv]/ret.31(DetectionModel::nndct_conv2d_26)
        self.module_27 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=True) #DetectionModel::DetectionModel/C3[model]/C3[4]/Sequential[m]/Bottleneck[1]/Conv[cv1]/LeakyReLU[act]/8966(DetectionModel::nndct_leaky_relu_27)
        self.module_28 = py_nndct.nn.Conv2d(in_channels=32, out_channels=32, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #DetectionModel::DetectionModel/C3[model]/C3[4]/Sequential[m]/Bottleneck[1]/Conv[cv2]/Conv2d[conv]/ret.33(DetectionModel::nndct_conv2d_28)
        self.module_29 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=True) #DetectionModel::DetectionModel/C3[model]/C3[4]/Sequential[m]/Bottleneck[1]/Conv[cv2]/LeakyReLU[act]/8988(DetectionModel::nndct_leaky_relu_29)
        self.module_30 = py_nndct.nn.Add() #DetectionModel::DetectionModel/C3[model]/C3[4]/Sequential[m]/Bottleneck[1]/ret.35(DetectionModel::nndct_elemwise_add_30)
        self.module_31 = py_nndct.nn.Conv2d(in_channels=64, out_channels=32, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #DetectionModel::DetectionModel/C3[model]/C3[4]/Conv[cv2]/Conv2d[conv]/ret.37(DetectionModel::nndct_conv2d_31)
        self.module_32 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=True) #DetectionModel::DetectionModel/C3[model]/C3[4]/Conv[cv2]/LeakyReLU[act]/9013(DetectionModel::nndct_leaky_relu_32)
        self.module_33 = py_nndct.nn.Cat() #DetectionModel::DetectionModel/C3[model]/C3[4]/ret.39(DetectionModel::nndct_concat_33)
        self.module_34 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #DetectionModel::DetectionModel/C3[model]/C3[4]/Conv[cv3]/Conv2d[conv]/ret.41(DetectionModel::nndct_conv2d_34)
        self.module_35 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=True) #DetectionModel::DetectionModel/C3[model]/C3[4]/Conv[cv3]/LeakyReLU[act]/9039(DetectionModel::nndct_leaky_relu_35)
        self.module_36 = py_nndct.nn.Conv2d(in_channels=64, out_channels=128, kernel_size=[3, 3], stride=[2, 2], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #DetectionModel::DetectionModel/Conv[model]/Conv[5]/Conv2d[conv]/ret.43(DetectionModel::nndct_conv2d_36)
        self.module_37 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=True) #DetectionModel::DetectionModel/Conv[model]/Conv[5]/LeakyReLU[act]/9061(DetectionModel::nndct_leaky_relu_37)
        self.module_38 = py_nndct.nn.Conv2d(in_channels=128, out_channels=64, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #DetectionModel::DetectionModel/C3[model]/C3[6]/Conv[cv1]/Conv2d[conv]/ret.45(DetectionModel::nndct_conv2d_38)
        self.module_39 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=True) #DetectionModel::DetectionModel/C3[model]/C3[6]/Conv[cv1]/LeakyReLU[act]/9083(DetectionModel::nndct_leaky_relu_39)
        self.module_40 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #DetectionModel::DetectionModel/C3[model]/C3[6]/Sequential[m]/Bottleneck[0]/Conv[cv1]/Conv2d[conv]/ret.47(DetectionModel::nndct_conv2d_40)
        self.module_41 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=True) #DetectionModel::DetectionModel/C3[model]/C3[6]/Sequential[m]/Bottleneck[0]/Conv[cv1]/LeakyReLU[act]/9105(DetectionModel::nndct_leaky_relu_41)
        self.module_42 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #DetectionModel::DetectionModel/C3[model]/C3[6]/Sequential[m]/Bottleneck[0]/Conv[cv2]/Conv2d[conv]/ret.49(DetectionModel::nndct_conv2d_42)
        self.module_43 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=True) #DetectionModel::DetectionModel/C3[model]/C3[6]/Sequential[m]/Bottleneck[0]/Conv[cv2]/LeakyReLU[act]/9127(DetectionModel::nndct_leaky_relu_43)
        self.module_44 = py_nndct.nn.Add() #DetectionModel::DetectionModel/C3[model]/C3[6]/Sequential[m]/Bottleneck[0]/ret.51(DetectionModel::nndct_elemwise_add_44)
        self.module_45 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #DetectionModel::DetectionModel/C3[model]/C3[6]/Sequential[m]/Bottleneck[1]/Conv[cv1]/Conv2d[conv]/ret.53(DetectionModel::nndct_conv2d_45)
        self.module_46 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=True) #DetectionModel::DetectionModel/C3[model]/C3[6]/Sequential[m]/Bottleneck[1]/Conv[cv1]/LeakyReLU[act]/9152(DetectionModel::nndct_leaky_relu_46)
        self.module_47 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #DetectionModel::DetectionModel/C3[model]/C3[6]/Sequential[m]/Bottleneck[1]/Conv[cv2]/Conv2d[conv]/ret.55(DetectionModel::nndct_conv2d_47)
        self.module_48 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=True) #DetectionModel::DetectionModel/C3[model]/C3[6]/Sequential[m]/Bottleneck[1]/Conv[cv2]/LeakyReLU[act]/9174(DetectionModel::nndct_leaky_relu_48)
        self.module_49 = py_nndct.nn.Add() #DetectionModel::DetectionModel/C3[model]/C3[6]/Sequential[m]/Bottleneck[1]/ret.57(DetectionModel::nndct_elemwise_add_49)
        self.module_50 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #DetectionModel::DetectionModel/C3[model]/C3[6]/Sequential[m]/Bottleneck[2]/Conv[cv1]/Conv2d[conv]/ret.59(DetectionModel::nndct_conv2d_50)
        self.module_51 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=True) #DetectionModel::DetectionModel/C3[model]/C3[6]/Sequential[m]/Bottleneck[2]/Conv[cv1]/LeakyReLU[act]/9199(DetectionModel::nndct_leaky_relu_51)
        self.module_52 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #DetectionModel::DetectionModel/C3[model]/C3[6]/Sequential[m]/Bottleneck[2]/Conv[cv2]/Conv2d[conv]/ret.61(DetectionModel::nndct_conv2d_52)
        self.module_53 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=True) #DetectionModel::DetectionModel/C3[model]/C3[6]/Sequential[m]/Bottleneck[2]/Conv[cv2]/LeakyReLU[act]/9221(DetectionModel::nndct_leaky_relu_53)
        self.module_54 = py_nndct.nn.Add() #DetectionModel::DetectionModel/C3[model]/C3[6]/Sequential[m]/Bottleneck[2]/ret.63(DetectionModel::nndct_elemwise_add_54)
        self.module_55 = py_nndct.nn.Conv2d(in_channels=128, out_channels=64, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #DetectionModel::DetectionModel/C3[model]/C3[6]/Conv[cv2]/Conv2d[conv]/ret.65(DetectionModel::nndct_conv2d_55)
        self.module_56 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=True) #DetectionModel::DetectionModel/C3[model]/C3[6]/Conv[cv2]/LeakyReLU[act]/9246(DetectionModel::nndct_leaky_relu_56)
        self.module_57 = py_nndct.nn.Cat() #DetectionModel::DetectionModel/C3[model]/C3[6]/ret.67(DetectionModel::nndct_concat_57)
        self.module_58 = py_nndct.nn.Conv2d(in_channels=128, out_channels=128, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #DetectionModel::DetectionModel/C3[model]/C3[6]/Conv[cv3]/Conv2d[conv]/ret.69(DetectionModel::nndct_conv2d_58)
        self.module_59 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=True) #DetectionModel::DetectionModel/C3[model]/C3[6]/Conv[cv3]/LeakyReLU[act]/9272(DetectionModel::nndct_leaky_relu_59)
        self.module_60 = py_nndct.nn.Conv2d(in_channels=128, out_channels=256, kernel_size=[3, 3], stride=[2, 2], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #DetectionModel::DetectionModel/Conv[model]/Conv[7]/Conv2d[conv]/ret.71(DetectionModel::nndct_conv2d_60)
        self.module_61 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=True) #DetectionModel::DetectionModel/Conv[model]/Conv[7]/LeakyReLU[act]/9294(DetectionModel::nndct_leaky_relu_61)
        self.module_62 = py_nndct.nn.Conv2d(in_channels=256, out_channels=128, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #DetectionModel::DetectionModel/C3[model]/C3[8]/Conv[cv1]/Conv2d[conv]/ret.73(DetectionModel::nndct_conv2d_62)
        self.module_63 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=True) #DetectionModel::DetectionModel/C3[model]/C3[8]/Conv[cv1]/LeakyReLU[act]/9316(DetectionModel::nndct_leaky_relu_63)
        self.module_64 = py_nndct.nn.Conv2d(in_channels=128, out_channels=128, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #DetectionModel::DetectionModel/C3[model]/C3[8]/Sequential[m]/Bottleneck[0]/Conv[cv1]/Conv2d[conv]/ret.75(DetectionModel::nndct_conv2d_64)
        self.module_65 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=True) #DetectionModel::DetectionModel/C3[model]/C3[8]/Sequential[m]/Bottleneck[0]/Conv[cv1]/LeakyReLU[act]/9338(DetectionModel::nndct_leaky_relu_65)
        self.module_66 = py_nndct.nn.Conv2d(in_channels=128, out_channels=128, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #DetectionModel::DetectionModel/C3[model]/C3[8]/Sequential[m]/Bottleneck[0]/Conv[cv2]/Conv2d[conv]/ret.77(DetectionModel::nndct_conv2d_66)
        self.module_67 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=True) #DetectionModel::DetectionModel/C3[model]/C3[8]/Sequential[m]/Bottleneck[0]/Conv[cv2]/LeakyReLU[act]/9360(DetectionModel::nndct_leaky_relu_67)
        self.module_68 = py_nndct.nn.Add() #DetectionModel::DetectionModel/C3[model]/C3[8]/Sequential[m]/Bottleneck[0]/ret.79(DetectionModel::nndct_elemwise_add_68)
        self.module_69 = py_nndct.nn.Conv2d(in_channels=256, out_channels=128, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #DetectionModel::DetectionModel/C3[model]/C3[8]/Conv[cv2]/Conv2d[conv]/ret.81(DetectionModel::nndct_conv2d_69)
        self.module_70 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=True) #DetectionModel::DetectionModel/C3[model]/C3[8]/Conv[cv2]/LeakyReLU[act]/9385(DetectionModel::nndct_leaky_relu_70)
        self.module_71 = py_nndct.nn.Cat() #DetectionModel::DetectionModel/C3[model]/C3[8]/ret.83(DetectionModel::nndct_concat_71)
        self.module_72 = py_nndct.nn.Conv2d(in_channels=256, out_channels=256, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #DetectionModel::DetectionModel/C3[model]/C3[8]/Conv[cv3]/Conv2d[conv]/ret.85(DetectionModel::nndct_conv2d_72)
        self.module_73 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=True) #DetectionModel::DetectionModel/C3[model]/C3[8]/Conv[cv3]/LeakyReLU[act]/9411(DetectionModel::nndct_leaky_relu_73)
        self.module_74 = py_nndct.nn.Conv2d(in_channels=256, out_channels=128, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #DetectionModel::DetectionModel/SPPF[model]/SPPF[9]/Conv[cv1]/Conv2d[conv]/ret.87(DetectionModel::nndct_conv2d_74)
        self.module_75 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=True) #DetectionModel::DetectionModel/SPPF[model]/SPPF[9]/Conv[cv1]/LeakyReLU[act]/9433(DetectionModel::nndct_leaky_relu_75)
        self.module_76 = py_nndct.nn.MaxPool2d(kernel_size=[5, 5], stride=[1, 1], padding=[2, 2], dilation=[1, 1], ceil_mode=False) #DetectionModel::DetectionModel/SPPF[model]/SPPF[9]/MaxPool2d[m]/9448(DetectionModel::nndct_maxpool_76)
        self.module_77 = py_nndct.nn.MaxPool2d(kernel_size=[5, 5], stride=[1, 1], padding=[2, 2], dilation=[1, 1], ceil_mode=False) #DetectionModel::DetectionModel/SPPF[model]/SPPF[9]/MaxPool2d[m]/9464(DetectionModel::nndct_maxpool_77)
        self.module_78 = py_nndct.nn.MaxPool2d(kernel_size=[5, 5], stride=[1, 1], padding=[2, 2], dilation=[1, 1], ceil_mode=False) #DetectionModel::DetectionModel/SPPF[model]/SPPF[9]/MaxPool2d[m]/9480(DetectionModel::nndct_maxpool_78)
        self.module_79 = py_nndct.nn.Cat() #DetectionModel::DetectionModel/SPPF[model]/SPPF[9]/ret.89(DetectionModel::nndct_concat_79)
        self.module_80 = py_nndct.nn.Conv2d(in_channels=512, out_channels=256, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #DetectionModel::DetectionModel/SPPF[model]/SPPF[9]/Conv[cv2]/Conv2d[conv]/ret.91(DetectionModel::nndct_conv2d_80)
        self.module_81 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=True) #DetectionModel::DetectionModel/SPPF[model]/SPPF[9]/Conv[cv2]/LeakyReLU[act]/9507(DetectionModel::nndct_leaky_relu_81)
        self.module_82 = py_nndct.nn.Conv2d(in_channels=256, out_channels=128, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #DetectionModel::DetectionModel/Conv[model]/Conv[10]/Conv2d[conv]/ret.93(DetectionModel::nndct_conv2d_82)
        self.module_83 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=True) #DetectionModel::DetectionModel/Conv[model]/Conv[10]/LeakyReLU[act]/9529(DetectionModel::nndct_leaky_relu_83)
        self.module_84 = py_nndct.nn.Interpolate() #DetectionModel::DetectionModel/Upsample[model]/Upsample[11]/ret.95(DetectionModel::nndct_resize_84)
        self.module_85 = py_nndct.nn.Cat() #DetectionModel::DetectionModel/Concat[model]/Concat[12]/ret.97(DetectionModel::nndct_concat_85)
        self.module_86 = py_nndct.nn.Conv2d(in_channels=256, out_channels=64, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #DetectionModel::DetectionModel/C3[model]/C3[13]/Conv[cv1]/Conv2d[conv]/ret.99(DetectionModel::nndct_conv2d_86)
        self.module_87 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=True) #DetectionModel::DetectionModel/C3[model]/C3[13]/Conv[cv1]/LeakyReLU[act]/9561(DetectionModel::nndct_leaky_relu_87)
        self.module_88 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #DetectionModel::DetectionModel/C3[model]/C3[13]/Sequential[m]/Bottleneck[0]/Conv[cv1]/Conv2d[conv]/ret.101(DetectionModel::nndct_conv2d_88)
        self.module_89 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=True) #DetectionModel::DetectionModel/C3[model]/C3[13]/Sequential[m]/Bottleneck[0]/Conv[cv1]/LeakyReLU[act]/9583(DetectionModel::nndct_leaky_relu_89)
        self.module_90 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #DetectionModel::DetectionModel/C3[model]/C3[13]/Sequential[m]/Bottleneck[0]/Conv[cv2]/Conv2d[conv]/ret.103(DetectionModel::nndct_conv2d_90)
        self.module_91 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=True) #DetectionModel::DetectionModel/C3[model]/C3[13]/Sequential[m]/Bottleneck[0]/Conv[cv2]/LeakyReLU[act]/9605(DetectionModel::nndct_leaky_relu_91)
        self.module_92 = py_nndct.nn.Conv2d(in_channels=256, out_channels=64, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #DetectionModel::DetectionModel/C3[model]/C3[13]/Conv[cv2]/Conv2d[conv]/ret.105(DetectionModel::nndct_conv2d_92)
        self.module_93 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=True) #DetectionModel::DetectionModel/C3[model]/C3[13]/Conv[cv2]/LeakyReLU[act]/9627(DetectionModel::nndct_leaky_relu_93)
        self.module_94 = py_nndct.nn.Cat() #DetectionModel::DetectionModel/C3[model]/C3[13]/ret.107(DetectionModel::nndct_concat_94)
        self.module_95 = py_nndct.nn.Conv2d(in_channels=128, out_channels=128, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #DetectionModel::DetectionModel/C3[model]/C3[13]/Conv[cv3]/Conv2d[conv]/ret.109(DetectionModel::nndct_conv2d_95)
        self.module_96 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=True) #DetectionModel::DetectionModel/C3[model]/C3[13]/Conv[cv3]/LeakyReLU[act]/9653(DetectionModel::nndct_leaky_relu_96)
        self.module_97 = py_nndct.nn.Conv2d(in_channels=128, out_channels=64, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #DetectionModel::DetectionModel/Conv[model]/Conv[14]/Conv2d[conv]/ret.111(DetectionModel::nndct_conv2d_97)
        self.module_98 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=True) #DetectionModel::DetectionModel/Conv[model]/Conv[14]/LeakyReLU[act]/9675(DetectionModel::nndct_leaky_relu_98)
        self.module_99 = py_nndct.nn.Interpolate() #DetectionModel::DetectionModel/Upsample[model]/Upsample[15]/ret.113(DetectionModel::nndct_resize_99)
        self.module_100 = py_nndct.nn.Cat() #DetectionModel::DetectionModel/Concat[model]/Concat[16]/ret.115(DetectionModel::nndct_concat_100)
        self.module_101 = py_nndct.nn.Conv2d(in_channels=128, out_channels=32, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #DetectionModel::DetectionModel/C3[model]/C3[17]/Conv[cv1]/Conv2d[conv]/ret.117(DetectionModel::nndct_conv2d_101)
        self.module_102 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=True) #DetectionModel::DetectionModel/C3[model]/C3[17]/Conv[cv1]/LeakyReLU[act]/9707(DetectionModel::nndct_leaky_relu_102)
        self.module_103 = py_nndct.nn.Conv2d(in_channels=32, out_channels=32, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #DetectionModel::DetectionModel/C3[model]/C3[17]/Sequential[m]/Bottleneck[0]/Conv[cv1]/Conv2d[conv]/ret.119(DetectionModel::nndct_conv2d_103)
        self.module_104 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=True) #DetectionModel::DetectionModel/C3[model]/C3[17]/Sequential[m]/Bottleneck[0]/Conv[cv1]/LeakyReLU[act]/9729(DetectionModel::nndct_leaky_relu_104)
        self.module_105 = py_nndct.nn.Conv2d(in_channels=32, out_channels=32, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #DetectionModel::DetectionModel/C3[model]/C3[17]/Sequential[m]/Bottleneck[0]/Conv[cv2]/Conv2d[conv]/ret.121(DetectionModel::nndct_conv2d_105)
        self.module_106 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=True) #DetectionModel::DetectionModel/C3[model]/C3[17]/Sequential[m]/Bottleneck[0]/Conv[cv2]/LeakyReLU[act]/9751(DetectionModel::nndct_leaky_relu_106)
        self.module_107 = py_nndct.nn.Conv2d(in_channels=128, out_channels=32, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #DetectionModel::DetectionModel/C3[model]/C3[17]/Conv[cv2]/Conv2d[conv]/ret.123(DetectionModel::nndct_conv2d_107)
        self.module_108 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=True) #DetectionModel::DetectionModel/C3[model]/C3[17]/Conv[cv2]/LeakyReLU[act]/9773(DetectionModel::nndct_leaky_relu_108)
        self.module_109 = py_nndct.nn.Cat() #DetectionModel::DetectionModel/C3[model]/C3[17]/ret.125(DetectionModel::nndct_concat_109)
        self.module_110 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #DetectionModel::DetectionModel/C3[model]/C3[17]/Conv[cv3]/Conv2d[conv]/ret.127(DetectionModel::nndct_conv2d_110)
        self.module_111 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=True) #DetectionModel::DetectionModel/C3[model]/C3[17]/Conv[cv3]/LeakyReLU[act]/9799(DetectionModel::nndct_leaky_relu_111)
        self.module_112 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[3, 3], stride=[2, 2], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #DetectionModel::DetectionModel/Conv[model]/Conv[18]/Conv2d[conv]/ret.129(DetectionModel::nndct_conv2d_112)
        self.module_113 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=True) #DetectionModel::DetectionModel/Conv[model]/Conv[18]/LeakyReLU[act]/9821(DetectionModel::nndct_leaky_relu_113)
        self.module_114 = py_nndct.nn.Cat() #DetectionModel::DetectionModel/Concat[model]/Concat[19]/ret.131(DetectionModel::nndct_concat_114)
        self.module_115 = py_nndct.nn.Conv2d(in_channels=128, out_channels=64, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #DetectionModel::DetectionModel/C3[model]/C3[20]/Conv[cv1]/Conv2d[conv]/ret.133(DetectionModel::nndct_conv2d_115)
        self.module_116 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=True) #DetectionModel::DetectionModel/C3[model]/C3[20]/Conv[cv1]/LeakyReLU[act]/9847(DetectionModel::nndct_leaky_relu_116)
        self.module_117 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #DetectionModel::DetectionModel/C3[model]/C3[20]/Sequential[m]/Bottleneck[0]/Conv[cv1]/Conv2d[conv]/ret.135(DetectionModel::nndct_conv2d_117)
        self.module_118 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=True) #DetectionModel::DetectionModel/C3[model]/C3[20]/Sequential[m]/Bottleneck[0]/Conv[cv1]/LeakyReLU[act]/9869(DetectionModel::nndct_leaky_relu_118)
        self.module_119 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #DetectionModel::DetectionModel/C3[model]/C3[20]/Sequential[m]/Bottleneck[0]/Conv[cv2]/Conv2d[conv]/ret.137(DetectionModel::nndct_conv2d_119)
        self.module_120 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=True) #DetectionModel::DetectionModel/C3[model]/C3[20]/Sequential[m]/Bottleneck[0]/Conv[cv2]/LeakyReLU[act]/9891(DetectionModel::nndct_leaky_relu_120)
        self.module_121 = py_nndct.nn.Conv2d(in_channels=128, out_channels=64, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #DetectionModel::DetectionModel/C3[model]/C3[20]/Conv[cv2]/Conv2d[conv]/ret.139(DetectionModel::nndct_conv2d_121)
        self.module_122 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=True) #DetectionModel::DetectionModel/C3[model]/C3[20]/Conv[cv2]/LeakyReLU[act]/9913(DetectionModel::nndct_leaky_relu_122)
        self.module_123 = py_nndct.nn.Cat() #DetectionModel::DetectionModel/C3[model]/C3[20]/ret.141(DetectionModel::nndct_concat_123)
        self.module_124 = py_nndct.nn.Conv2d(in_channels=128, out_channels=128, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #DetectionModel::DetectionModel/C3[model]/C3[20]/Conv[cv3]/Conv2d[conv]/ret.143(DetectionModel::nndct_conv2d_124)
        self.module_125 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=True) #DetectionModel::DetectionModel/C3[model]/C3[20]/Conv[cv3]/LeakyReLU[act]/9939(DetectionModel::nndct_leaky_relu_125)
        self.module_126 = py_nndct.nn.Conv2d(in_channels=128, out_channels=128, kernel_size=[3, 3], stride=[2, 2], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #DetectionModel::DetectionModel/Conv[model]/Conv[21]/Conv2d[conv]/ret.145(DetectionModel::nndct_conv2d_126)
        self.module_127 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=True) #DetectionModel::DetectionModel/Conv[model]/Conv[21]/LeakyReLU[act]/9961(DetectionModel::nndct_leaky_relu_127)
        self.module_128 = py_nndct.nn.Cat() #DetectionModel::DetectionModel/Concat[model]/Concat[22]/ret.147(DetectionModel::nndct_concat_128)
        self.module_129 = py_nndct.nn.Conv2d(in_channels=256, out_channels=128, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #DetectionModel::DetectionModel/C3[model]/C3[23]/Conv[cv1]/Conv2d[conv]/ret.149(DetectionModel::nndct_conv2d_129)
        self.module_130 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=True) #DetectionModel::DetectionModel/C3[model]/C3[23]/Conv[cv1]/LeakyReLU[act]/9987(DetectionModel::nndct_leaky_relu_130)
        self.module_131 = py_nndct.nn.Conv2d(in_channels=128, out_channels=128, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #DetectionModel::DetectionModel/C3[model]/C3[23]/Sequential[m]/Bottleneck[0]/Conv[cv1]/Conv2d[conv]/ret.151(DetectionModel::nndct_conv2d_131)
        self.module_132 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=True) #DetectionModel::DetectionModel/C3[model]/C3[23]/Sequential[m]/Bottleneck[0]/Conv[cv1]/LeakyReLU[act]/10009(DetectionModel::nndct_leaky_relu_132)
        self.module_133 = py_nndct.nn.Conv2d(in_channels=128, out_channels=128, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #DetectionModel::DetectionModel/C3[model]/C3[23]/Sequential[m]/Bottleneck[0]/Conv[cv2]/Conv2d[conv]/ret.153(DetectionModel::nndct_conv2d_133)
        self.module_134 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=True) #DetectionModel::DetectionModel/C3[model]/C3[23]/Sequential[m]/Bottleneck[0]/Conv[cv2]/LeakyReLU[act]/10031(DetectionModel::nndct_leaky_relu_134)
        self.module_135 = py_nndct.nn.Conv2d(in_channels=256, out_channels=128, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #DetectionModel::DetectionModel/C3[model]/C3[23]/Conv[cv2]/Conv2d[conv]/ret.155(DetectionModel::nndct_conv2d_135)
        self.module_136 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=True) #DetectionModel::DetectionModel/C3[model]/C3[23]/Conv[cv2]/LeakyReLU[act]/10053(DetectionModel::nndct_leaky_relu_136)
        self.module_137 = py_nndct.nn.Cat() #DetectionModel::DetectionModel/C3[model]/C3[23]/ret.157(DetectionModel::nndct_concat_137)
        self.module_138 = py_nndct.nn.Conv2d(in_channels=256, out_channels=256, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #DetectionModel::DetectionModel/C3[model]/C3[23]/Conv[cv3]/Conv2d[conv]/ret.159(DetectionModel::nndct_conv2d_138)
        self.module_139 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=True) #DetectionModel::DetectionModel/C3[model]/C3[23]/Conv[cv3]/LeakyReLU[act]/10079(DetectionModel::nndct_leaky_relu_139)
        self.module_140 = py_nndct.nn.Conv2d(in_channels=64, out_channels=21, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #DetectionModel::DetectionModel/Detect[model]/Detect[24]/Conv2d[m]/ModuleList[0]/ret.161(DetectionModel::nndct_conv2d_140)
        self.module_141 = py_nndct.nn.Module('nndct_shape') #DetectionModel::DetectionModel/Detect[model]/Detect[24]/10101(DetectionModel::nndct_shape_141)
        self.module_142 = py_nndct.nn.Module('nndct_tensor') #DetectionModel::DetectionModel/Detect[model]/Detect[24]/r.1(DetectionModel::nndct_tensor_142)
        self.module_143 = py_nndct.nn.Module('nndct_shape') #DetectionModel::DetectionModel/Detect[model]/Detect[24]/10107(DetectionModel::nndct_shape_143)
        self.module_144 = py_nndct.nn.Module('nndct_tensor') #DetectionModel::DetectionModel/Detect[model]/Detect[24]/r.5(DetectionModel::nndct_tensor_144)
        self.module_145 = py_nndct.nn.Module('nndct_shape') #DetectionModel::DetectionModel/Detect[model]/Detect[24]/10110(DetectionModel::nndct_shape_145)
        self.module_146 = py_nndct.nn.Module('nndct_tensor') #DetectionModel::DetectionModel/Detect[model]/Detect[24]/r.7(DetectionModel::nndct_tensor_146)
        self.module_147 = py_nndct.nn.Int() #DetectionModel::DetectionModel/Detect[model]/Detect[24]/10113(DetectionModel::nndct_int_147)
        self.module_148 = py_nndct.nn.Int() #DetectionModel::DetectionModel/Detect[model]/Detect[24]/10116(DetectionModel::nndct_int_148)
        self.module_149 = py_nndct.nn.Int() #DetectionModel::DetectionModel/Detect[model]/Detect[24]/10118(DetectionModel::nndct_int_149)
        self.module_150 = py_nndct.nn.Module('nndct_reshape') #DetectionModel::DetectionModel/Detect[model]/Detect[24]/ret.163(DetectionModel::nndct_reshape_150)
        self.module_151 = py_nndct.nn.Module('nndct_permute') #DetectionModel::DetectionModel/Detect[model]/Detect[24]/ret.165(DetectionModel::nndct_permute_151)
        self.module_152 = py_nndct.nn.Module('nndct_contiguous') #DetectionModel::DetectionModel/Detect[model]/Detect[24]/ret.167(DetectionModel::nndct_contiguous_152)
        self.module_153 = py_nndct.nn.Conv2d(in_channels=128, out_channels=21, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #DetectionModel::DetectionModel/Detect[model]/Detect[24]/Conv2d[m]/ModuleList[1]/ret.169(DetectionModel::nndct_conv2d_153)
        self.module_154 = py_nndct.nn.Module('nndct_shape') #DetectionModel::DetectionModel/Detect[model]/Detect[24]/10156(DetectionModel::nndct_shape_154)
        self.module_155 = py_nndct.nn.Module('nndct_tensor') #DetectionModel::DetectionModel/Detect[model]/Detect[24]/r.9(DetectionModel::nndct_tensor_155)
        self.module_156 = py_nndct.nn.Module('nndct_shape') #DetectionModel::DetectionModel/Detect[model]/Detect[24]/10162(DetectionModel::nndct_shape_156)
        self.module_157 = py_nndct.nn.Module('nndct_tensor') #DetectionModel::DetectionModel/Detect[model]/Detect[24]/r.13(DetectionModel::nndct_tensor_157)
        self.module_158 = py_nndct.nn.Module('nndct_shape') #DetectionModel::DetectionModel/Detect[model]/Detect[24]/10165(DetectionModel::nndct_shape_158)
        self.module_159 = py_nndct.nn.Module('nndct_tensor') #DetectionModel::DetectionModel/Detect[model]/Detect[24]/r.15(DetectionModel::nndct_tensor_159)
        self.module_160 = py_nndct.nn.Int() #DetectionModel::DetectionModel/Detect[model]/Detect[24]/10168(DetectionModel::nndct_int_160)
        self.module_161 = py_nndct.nn.Int() #DetectionModel::DetectionModel/Detect[model]/Detect[24]/10171(DetectionModel::nndct_int_161)
        self.module_162 = py_nndct.nn.Int() #DetectionModel::DetectionModel/Detect[model]/Detect[24]/10173(DetectionModel::nndct_int_162)
        self.module_163 = py_nndct.nn.Module('nndct_reshape') #DetectionModel::DetectionModel/Detect[model]/Detect[24]/ret.171(DetectionModel::nndct_reshape_163)
        self.module_164 = py_nndct.nn.Module('nndct_permute') #DetectionModel::DetectionModel/Detect[model]/Detect[24]/ret.173(DetectionModel::nndct_permute_164)
        self.module_165 = py_nndct.nn.Module('nndct_contiguous') #DetectionModel::DetectionModel/Detect[model]/Detect[24]/ret.175(DetectionModel::nndct_contiguous_165)
        self.module_166 = py_nndct.nn.Conv2d(in_channels=256, out_channels=21, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #DetectionModel::DetectionModel/Detect[model]/Detect[24]/Conv2d[m]/ModuleList[2]/ret.177(DetectionModel::nndct_conv2d_166)
        self.module_167 = py_nndct.nn.Module('nndct_shape') #DetectionModel::DetectionModel/Detect[model]/Detect[24]/10211(DetectionModel::nndct_shape_167)
        self.module_168 = py_nndct.nn.Module('nndct_tensor') #DetectionModel::DetectionModel/Detect[model]/Detect[24]/r.17(DetectionModel::nndct_tensor_168)
        self.module_169 = py_nndct.nn.Module('nndct_shape') #DetectionModel::DetectionModel/Detect[model]/Detect[24]/10217(DetectionModel::nndct_shape_169)
        self.module_170 = py_nndct.nn.Module('nndct_tensor') #DetectionModel::DetectionModel/Detect[model]/Detect[24]/r.21(DetectionModel::nndct_tensor_170)
        self.module_171 = py_nndct.nn.Module('nndct_shape') #DetectionModel::DetectionModel/Detect[model]/Detect[24]/10220(DetectionModel::nndct_shape_171)
        self.module_172 = py_nndct.nn.Module('nndct_tensor') #DetectionModel::DetectionModel/Detect[model]/Detect[24]/r(DetectionModel::nndct_tensor_172)
        self.module_173 = py_nndct.nn.Int() #DetectionModel::DetectionModel/Detect[model]/Detect[24]/10223(DetectionModel::nndct_int_173)
        self.module_174 = py_nndct.nn.Int() #DetectionModel::DetectionModel/Detect[model]/Detect[24]/10226(DetectionModel::nndct_int_174)
        self.module_175 = py_nndct.nn.Int() #DetectionModel::DetectionModel/Detect[model]/Detect[24]/10228(DetectionModel::nndct_int_175)
        self.module_176 = py_nndct.nn.Module('nndct_reshape') #DetectionModel::DetectionModel/Detect[model]/Detect[24]/ret.179(DetectionModel::nndct_reshape_176)
        self.module_177 = py_nndct.nn.Module('nndct_permute') #DetectionModel::DetectionModel/Detect[model]/Detect[24]/ret.181(DetectionModel::nndct_permute_177)
        self.module_178 = py_nndct.nn.Module('nndct_contiguous') #DetectionModel::DetectionModel/Detect[model]/Detect[24]/ret(DetectionModel::nndct_contiguous_178)

    @py_nndct.nn.forward_processor
    def forward(self, *args):
        output_module_0 = self.module_0(input=args[0])
        output_module_0 = self.module_1(output_module_0)
        output_module_0 = self.module_2(output_module_0)
        output_module_0 = self.module_3(output_module_0)
        output_module_0 = self.module_4(output_module_0)
        output_module_5 = self.module_5(output_module_0)
        output_module_5 = self.module_6(output_module_5)
        output_module_7 = self.module_7(output_module_5)
        output_module_7 = self.module_8(output_module_7)
        output_module_7 = self.module_9(output_module_7)
        output_module_7 = self.module_10(output_module_7)
        output_module_11 = self.module_11(input=output_module_5, other=output_module_7, alpha=1)
        output_module_12 = self.module_12(output_module_0)
        output_module_12 = self.module_13(output_module_12)
        output_module_11 = self.module_14(dim=1, tensors=[output_module_11,output_module_12])
        output_module_11 = self.module_15(output_module_11)
        output_module_11 = self.module_16(output_module_11)
        output_module_11 = self.module_17(output_module_11)
        output_module_11 = self.module_18(output_module_11)
        output_module_19 = self.module_19(output_module_11)
        output_module_19 = self.module_20(output_module_19)
        output_module_21 = self.module_21(output_module_19)
        output_module_21 = self.module_22(output_module_21)
        output_module_21 = self.module_23(output_module_21)
        output_module_21 = self.module_24(output_module_21)
        output_module_25 = self.module_25(input=output_module_19, other=output_module_21, alpha=1)
        output_module_26 = self.module_26(output_module_25)
        output_module_26 = self.module_27(output_module_26)
        output_module_26 = self.module_28(output_module_26)
        output_module_26 = self.module_29(output_module_26)
        output_module_30 = self.module_30(input=output_module_25, other=output_module_26, alpha=1)
        output_module_31 = self.module_31(output_module_11)
        output_module_31 = self.module_32(output_module_31)
        output_module_30 = self.module_33(dim=1, tensors=[output_module_30,output_module_31])
        output_module_30 = self.module_34(output_module_30)
        output_module_30 = self.module_35(output_module_30)
        output_module_36 = self.module_36(output_module_30)
        output_module_36 = self.module_37(output_module_36)
        output_module_38 = self.module_38(output_module_36)
        output_module_38 = self.module_39(output_module_38)
        output_module_40 = self.module_40(output_module_38)
        output_module_40 = self.module_41(output_module_40)
        output_module_40 = self.module_42(output_module_40)
        output_module_40 = self.module_43(output_module_40)
        output_module_44 = self.module_44(input=output_module_38, other=output_module_40, alpha=1)
        output_module_45 = self.module_45(output_module_44)
        output_module_45 = self.module_46(output_module_45)
        output_module_45 = self.module_47(output_module_45)
        output_module_45 = self.module_48(output_module_45)
        output_module_49 = self.module_49(input=output_module_44, other=output_module_45, alpha=1)
        output_module_50 = self.module_50(output_module_49)
        output_module_50 = self.module_51(output_module_50)
        output_module_50 = self.module_52(output_module_50)
        output_module_50 = self.module_53(output_module_50)
        output_module_54 = self.module_54(input=output_module_49, other=output_module_50, alpha=1)
        output_module_55 = self.module_55(output_module_36)
        output_module_55 = self.module_56(output_module_55)
        output_module_54 = self.module_57(dim=1, tensors=[output_module_54,output_module_55])
        output_module_54 = self.module_58(output_module_54)
        output_module_54 = self.module_59(output_module_54)
        output_module_60 = self.module_60(output_module_54)
        output_module_60 = self.module_61(output_module_60)
        output_module_62 = self.module_62(output_module_60)
        output_module_62 = self.module_63(output_module_62)
        output_module_64 = self.module_64(output_module_62)
        output_module_64 = self.module_65(output_module_64)
        output_module_64 = self.module_66(output_module_64)
        output_module_64 = self.module_67(output_module_64)
        output_module_68 = self.module_68(input=output_module_62, other=output_module_64, alpha=1)
        output_module_69 = self.module_69(output_module_60)
        output_module_69 = self.module_70(output_module_69)
        output_module_68 = self.module_71(dim=1, tensors=[output_module_68,output_module_69])
        output_module_68 = self.module_72(output_module_68)
        output_module_68 = self.module_73(output_module_68)
        output_module_68 = self.module_74(output_module_68)
        output_module_68 = self.module_75(output_module_68)
        output_module_76 = self.module_76(output_module_68)
        output_module_77 = self.module_77(output_module_76)
        output_module_78 = self.module_78(output_module_77)
        output_module_79 = self.module_79(dim=1, tensors=[output_module_68,output_module_76,output_module_77,output_module_78])
        output_module_79 = self.module_80(output_module_79)
        output_module_79 = self.module_81(output_module_79)
        output_module_79 = self.module_82(output_module_79)
        output_module_79 = self.module_83(output_module_79)
        output_module_84 = self.module_84(input=output_module_79, size=None, scale_factor=[2.0,2.0], mode='nearest')
        output_module_84 = self.module_85(dim=1, tensors=[output_module_84,output_module_54])
        output_module_86 = self.module_86(output_module_84)
        output_module_86 = self.module_87(output_module_86)
        output_module_86 = self.module_88(output_module_86)
        output_module_86 = self.module_89(output_module_86)
        output_module_86 = self.module_90(output_module_86)
        output_module_86 = self.module_91(output_module_86)
        output_module_92 = self.module_92(output_module_84)
        output_module_92 = self.module_93(output_module_92)
        output_module_86 = self.module_94(dim=1, tensors=[output_module_86,output_module_92])
        output_module_86 = self.module_95(output_module_86)
        output_module_86 = self.module_96(output_module_86)
        output_module_86 = self.module_97(output_module_86)
        output_module_86 = self.module_98(output_module_86)
        output_module_99 = self.module_99(input=output_module_86, size=None, scale_factor=[2.0,2.0], mode='nearest')
        output_module_99 = self.module_100(dim=1, tensors=[output_module_99,output_module_30])
        output_module_101 = self.module_101(output_module_99)
        output_module_101 = self.module_102(output_module_101)
        output_module_101 = self.module_103(output_module_101)
        output_module_101 = self.module_104(output_module_101)
        output_module_101 = self.module_105(output_module_101)
        output_module_101 = self.module_106(output_module_101)
        output_module_107 = self.module_107(output_module_99)
        output_module_107 = self.module_108(output_module_107)
        output_module_101 = self.module_109(dim=1, tensors=[output_module_101,output_module_107])
        output_module_101 = self.module_110(output_module_101)
        output_module_101 = self.module_111(output_module_101)
        output_module_112 = self.module_112(output_module_101)
        output_module_112 = self.module_113(output_module_112)
        output_module_112 = self.module_114(dim=1, tensors=[output_module_112,output_module_86])
        output_module_115 = self.module_115(output_module_112)
        output_module_115 = self.module_116(output_module_115)
        output_module_115 = self.module_117(output_module_115)
        output_module_115 = self.module_118(output_module_115)
        output_module_115 = self.module_119(output_module_115)
        output_module_115 = self.module_120(output_module_115)
        output_module_121 = self.module_121(output_module_112)
        output_module_121 = self.module_122(output_module_121)
        output_module_115 = self.module_123(dim=1, tensors=[output_module_115,output_module_121])
        output_module_115 = self.module_124(output_module_115)
        output_module_115 = self.module_125(output_module_115)
        output_module_126 = self.module_126(output_module_115)
        output_module_126 = self.module_127(output_module_126)
        output_module_126 = self.module_128(dim=1, tensors=[output_module_126,output_module_79])
        output_module_129 = self.module_129(output_module_126)
        output_module_129 = self.module_130(output_module_129)
        output_module_129 = self.module_131(output_module_129)
        output_module_129 = self.module_132(output_module_129)
        output_module_129 = self.module_133(output_module_129)
        output_module_129 = self.module_134(output_module_129)
        output_module_135 = self.module_135(output_module_126)
        output_module_135 = self.module_136(output_module_135)
        output_module_129 = self.module_137(dim=1, tensors=[output_module_129,output_module_135])
        output_module_129 = self.module_138(output_module_129)
        output_module_129 = self.module_139(output_module_129)
        output_module_140 = self.module_140(output_module_101)
        output_module_141 = self.module_141(input=output_module_140, dim=0)
        output_module_141 = self.module_142(data=output_module_141, dtype=torch.int, device='cpu')
        output_module_143 = self.module_143(input=output_module_140, dim=2)
        output_module_143 = self.module_144(data=output_module_143, dtype=torch.int, device='cpu')
        output_module_145 = self.module_145(input=output_module_140, dim=3)
        output_module_145 = self.module_146(data=output_module_145, dtype=torch.int, device='cpu')
        output_module_141 = self.module_147(input=output_module_141)
        output_module_143 = self.module_148(input=output_module_143)
        output_module_145 = self.module_149(input=output_module_145)
        output_module_150 = self.module_150(input=output_module_140, shape=[output_module_141,3,7,output_module_143,output_module_145])
        output_module_150 = self.module_151(dims=[0,1,3,4,2], input=output_module_150)
        output_module_150 = self.module_152(output_module_150)
        output_module_153 = self.module_153(output_module_115)
        output_module_154 = self.module_154(input=output_module_153, dim=0)
        output_module_154 = self.module_155(data=output_module_154, dtype=torch.int, device='cpu')
        output_module_156 = self.module_156(input=output_module_153, dim=2)
        output_module_156 = self.module_157(data=output_module_156, dtype=torch.int, device='cpu')
        output_module_158 = self.module_158(input=output_module_153, dim=3)
        output_module_158 = self.module_159(data=output_module_158, dtype=torch.int, device='cpu')
        output_module_154 = self.module_160(input=output_module_154)
        output_module_156 = self.module_161(input=output_module_156)
        output_module_158 = self.module_162(input=output_module_158)
        output_module_163 = self.module_163(input=output_module_153, shape=[output_module_154,3,7,output_module_156,output_module_158])
        output_module_163 = self.module_164(dims=[0,1,3,4,2], input=output_module_163)
        output_module_163 = self.module_165(output_module_163)
        output_module_129 = self.module_166(output_module_129)
        output_module_167 = self.module_167(input=output_module_129, dim=0)
        output_module_167 = self.module_168(data=output_module_167, dtype=torch.int, device='cpu')
        output_module_169 = self.module_169(input=output_module_129, dim=2)
        output_module_169 = self.module_170(data=output_module_169, dtype=torch.int, device='cpu')
        output_module_171 = self.module_171(input=output_module_129, dim=3)
        output_module_171 = self.module_172(data=output_module_171, dtype=torch.int, device='cpu')
        output_module_167 = self.module_173(input=output_module_167)
        output_module_169 = self.module_174(input=output_module_169)
        output_module_171 = self.module_175(input=output_module_171)
        output_module_176 = self.module_176(input=output_module_129, shape=[output_module_167,3,7,output_module_169,output_module_171])
        output_module_176 = self.module_177(dims=[0,1,3,4,2], input=output_module_176)
        output_module_176 = self.module_178(output_module_176)
        return (output_module_150,output_module_163,output_module_176)
